module.exports = {
  feedLinks: { 
    "https://www.clarin.com/rss/lo-ultimo/": "Argentina",
    // "https://www.cronica.com.ar/feed/feed.xml": "Argentina",
    "https://www.lanacion.com.ar/arc/outboundfeeds/rss/?outputType=xml": "Argentina",
    "https://www.pagina12.com.ar/rss/portada": "Argentina",
    "https://elintransigente.com/feed/": "Argentina",
    "https://www.cronista.com/files/rss/news.xml": "Argentina",
    "https://www.diariodecuyo.com.ar/rss/rss.xml": "Argentina",
    "https://www.eldia.com/.rss": "Argentina",
    "https://www.losandes.com.ar/arcio/rss/": "Argentina",
    "https://feeds.feedburner.com/elliberaldigital": "Argentina",
    "https://www.diarioregistrado.com/rss.xml": "Argentina",
    "https://www.lavoz.com.ar/arc/outboundfeeds/feeds/rss/?outputType=xml": "Argentina",
    "https://www.perfil.com/feed": "Argentina",
    "https://feeds.feedburner.com/LaGaceta-General": "Argentina",
    "https://www.infobae.com/argentina-rss.xml": "Argentina",
    "https://elmundo.com.bo/feed/": "Bolivia",
    "https://eldeber.com.bo/rss/feed": "Bolivia",
    "https://www.la-razon.com/feed/": "Bolivia",
    "https://www.lostiempos.com/rss/portada": "Bolivia",
    "https://www.eldiario.net/portal/feed/": "Bolivia",
    "https://www.paginasiete.bo/rss/nacional.xml": "Bolivia",
    "https://www.df.cl/noticias/site/list/port/rss.xml": "Chile",
    "https://www.latercera.com/arcio/rss/": "Chile",
    "https://cambio21.cl/rss": "Chile",
    "https://lahora.cl/feed/": "Chile",
    "https://www.cooperativa.cl/noticias/site/tax/port/all/rss_3___1.xml":"Chile",
    "https://www.elmostrador.cl/destacado/feed/": "Chile",
    "https://www.elclarin.cl/feed/": "Chile",
    "https://www.lanacion.cl/feed/": "Chile",
    "https://www.ladiscusion.cl/feed/": "Chile",
    "https://www.elrancaguino.cl/feed/": "Chile",
    "https://www.theclinic.cl/feed/": "Chile",
    "https://www.eldinamo.cl/feed/": "Chile",
    "https://www.desdeabajo.info/feed": "Colombia",
    "https://extra.com.co/feed/": "Colombia",
    "https://www.qhubo.com/feed/": "Colombia",
    "https://www.las2orillas.co/feed/": "Colombia",
    "https://lalibertad.com.co/feed/": "Colombia",
    "https://www.periodicolacampana.com/feed/": "Colombia",
    "https://choco7dias.com/feed/": "Colombia",
    "https://prensalibrecasanare.com/rss.xml": "Colombia",
    "https://www.elinformador.com.co/index.php?format=feed&type=rss":"Colombia",
    "https://www.elpaisvallenato.com/feed/": "Colombia",
    "https://elpilon.com.co/feed/": "Colombia",
    "https://www.eldiario.com.co/feed/": "Colombia",
    "https://eldiariodelllano.com/feed/": "Colombia",
    "https://diariodelhuila.com/feed/": "Colombia",
    "https://www.centropolismedellin.com/feed/": "Colombia",
    "https://www.elnuevosiglo.com.co/rss.xml": "Colombia",
    "https://www.metroworldnews.com/arc/outboundfeeds/rss/?outputType=xml": "Colombia",
    "https://www.cronicadelquindio.com/rss-feed/colombia": "Colombia",
    "https://laopinion.com/feed/": "Colombia",
    "https://www.elpais.com.co/rss": "Colombia",
    "https://www.eltiempo.com/rss/colombia.xml": "Colombia",
    "https://www.lanacion.com.co/feed/": "Colombia",
    "https://occidente.co/feed/": "Colombia",
    "https://www.teleantioquia.co/noticias/feed/": "Colombia",
    "https://www.minuto30.com/feed/": "Colombia",
    "https://www.kienyke.com/feed": "Colombia",
    "https://www.lateja.cr/arc/outboundfeeds/rss/?outputType=xml": "Costa Rica",
    "https://www.nacion.com/arc/outboundfeeds/rss/?outputType=xml": "Costa Rica",
    "https://www.larepublica.net/rss/portada.xml": "Costa Rica",
    "http://www.cubadebate.cu/feed/": "Cuba",
    "https://www.prensa-latina.cu/feed?rss-2": "Cuba",
    "https://eldia.com.do/feed/": "Dominican Republic",
    // "https://elnuevodiario.com.do/feed/": "Dominican Republic",
    "https://www.diariolibre.com/rss/portada.xml": "Dominican Republic",
    "https://listindiario.com/rss/portada/": "Dominican Republic",
    "https://hoy.com.do/feed/": "Dominican Republic",
    "https://lanacion.com.ec/feed/": "Ecuador",
    "https://elmercurio.com.ec/feed/": "Ecuador",
    "https://elnorte.ec/feed/": "Ecuador",
    "https://www.diariolosandes.com.ec/feed/": "Ecuador",
    "https://www.larepublica.ec/feed/": "Ecuador",
    "https://www.laprensa.com.ec/feed/": "Ecuador",
    "https://cronica.com.ec/feed/": "Ecuador",
    "https://www.ultimasnoticias.ec/rss/": "Ecuador",
    "https://www.elcomercio.com/feed/": "Ecuador",
    "https://www.lahora.com.ec/feed/": "Ecuador",
    "https://diariolahuella.com/feed/": "El Salvador",
    "https://diariolatino.net/feed/": "El Salvador",
    "https://diariolibresv.com/feed/": "El Salvador",
    "https://www.elmetropolitanodigital.com/feed/": "El Salvador",
    "https://www.elsalvadortimes.com/rss/": "El Salvador",
    "https://www.periodicoequilibrium.com/feed/": "El Salvador",
    "https://www.102nueve.com/feed/": "El Salvador",
    "http://elvicentino.com/feed/": "El Salvador",
    "http://elpais.com.sv/feed/": "El Salvador",
    "https://ultimahora.sv/feed/": "El Salvador",
    // "https://lapagina.com.sv/feed/": "El Salvador",
    "https://informatvx.com/feed/": "El Salvador",
    "https://www.diariocolatino.com/feed/": "El Salvador",
    "https://diario.elmundo.sv/rssFeed/13": "El Salvador",
    "https://megavision.com.sv/feed/":"El Salvador",    
    "https://croniosv.com/feed/": "El Salvador",
    "https://www.prensalibre.com/feed/#": "Guatemala",
    "https://lahora.gt/feed/": "Guatemala",
    "https://elperiodico.com.gt/feed/": "Guatemala",
    "https://dca.gob.gt/noticias-guatemala-diario-centro-america/feed/": "Guatemala",
    "https://www.publinews.gt/gt/feed": "Guatemala",
    "https://crnnoticias.com/feed/": "Guatemala",
    "https://emisorasunidas.com/feed/": "Guatemala",
    "https://republica.gt/feed": "Guatemala",
    "https://elsiglo.com.gt/feed/": "Guatemala",
    "https://www.perspectiva.gt/feed/": "Guatemala",
    "https://publicogt.com/feed/": "Guatemala",
    "https://www.guatemala.com/feed/": "Guatemala",
    "https://www.laprensa.hn/rss/portada": "Honduras",
    "https://contextohn.com/feed/": "Honduras",
    "https://www.diariomas.hn/feed/": "Honduras",
    "https://www.elheraldo.hn/rss/portada.xml": "Honduras",
    "https://heraldodemexico.com.mx/rss/feed.html?r=4": "Mexico",
    "https://www.excelsior.com.mx/rss.xml": "Mexico",
    "https://www.milenio.com/rss": "Mexico",
    // "https://www.debate.com.mx/rss/feed.xml": "Mexico",
    "https://www.jornada.com.mx/feeds/rss": "Mexico",
    "https://www.publimetro.com.mx/arc/outboundfeeds/rss/category/noticias/mundo/?outputType=xml": "Mexico",
    "https://www.sinembargo.mx/feed": "Mexico",
    "https://editorial.aristeguinoticias.com/feed/": "Mexico",
    "https://www.razon.com.mx/rss/feed.xml": "Mexico",
    "https://www.sdpnoticias.com/arc/outboundfeeds/rss/?outputType=xml": "Mexico",
    "https://www.reforma.com/rss/portada.xml": "Mexico",
    "https://www.reporteindigo.com/feed/": "Mexico",
    "https://www.proceso.com.mx/rss/feed.html?r=1": "Mexico",
    "https://lasillarota.com/rss/feed.html?r=11": "Mexico",
    "https://www.24-horas.mx/feed/": "Mexico",
    "https://www.cronica.com.mx/rss/": "Mexico",
    "https://www.ejecentral.com.mx/feed/": "Mexico",
    "https://www.capitalmexico.com.mx/feed/": "Mexico",
    "https://www.pasala.com.mx/feed": "Mexico",
    "https://noticiasenlamira.com/feed/": "Mexico",
    "https://www.maspormas.com/rss/": "Mexico",
    "https://unomasuno.com.mx/feed/": "Mexico",
    "https://periodicoeldia.mx/feed/": "Mexico",
    "https://www.elnovedades.com.mx/feed/": "Mexico",
    "https://miled.com/feed/": "Mexico",
    "https://www.20minutos.es/rss/": "Mexico",
    "https://newsreportmx.com/feed/": "Mexico",
    "https://grupometropoli.net/feed/": "Mexico",
    "http://expresochiapas.com/noticias/feed/": "Mexico",
    "https://8columnas.com.mx/feed/": "Mexico",
    "https://www.mural.com.mx/rss/portada.xml": "Mexico",
    "http://imparcialoaxaca.mx/feed/": "Mexico",
    "https://www.informador.mx/rss/mexico.xml": "Mexico",
    "https://eldeforma.com/feed/": "Mexico",
    "https://www.elnorte.com/rss/portada.xml": "Mexico",
    "https://www.elfinanciero.com.mx/arc/outboundfeeds/rss/?outputType=xml": "Mexico",
    "https://diario.mx/jrz/media/sitemaps/rss.xml": "Mexico",
    "https://vanguardia.com.mx/rss.xml": "Mexico",
    "https://www.elsiglodetorreon.com.mx/index.xml": "Mexico",
    "https://plazajuarez.mx/feed/": "Mexico",
    "https://www.capitalqueretaro.com.mx/category/nacional/feed/": "Mexico",
    "http://naimexico.com/feed/": "Mexico",
    "https://canal2tv.com/feed/": "Nicaragua",
    "https://www.articulo66.com/feed/": "Nicaragua",
    "https://confidencial.digital/feed/": "Nicaragua",
    "https://laverdadnica.com/feed/": "Nicaragua",
    "https://www.desdechinandega.com/feed": "Nicaragua",
    "https://www.lasandino.com.ni/feed/": "Nicaragua",
    "https://nicaraguainvestiga.com/feed/": "Nicaragua",
    "https://www.despacho505.com/feed/": "Nicaragua",
    "https://nicaraguaactual.tv/feed/": "Nicaragua",
    "https://ipnicaragua.com/feed/": "Nicaragua",
    "http://149.56.20.237/rss?website=2": "Panama",
    "https://www.panama24horas.com.pa/feed/": "Panama",
    "https://eldigitalpanama.com/feed/": "Panama",
    "https://lagacetadepanama.com/feed/": "Panama",
    "https://bayanodigital.com/feed/": "Panama",
    "https://www.noticiasvip24.com/feed/": "Panama",
    "https://www.laestrella.com.pa/rss/": "Panama",
    "https://wayka.pe/feed/": "Peru",
    "https://www.caretas.pe/feed/": "Peru",
    "https://laprimera.pe/feed/": "Peru",
    "https://elperfil.pe/feed/": "Peru",
    "https://delpais.com.pe/feed/": "Peru",
    "https://www.peruinforma.com/feed/": "Peru",
    "https://www.lapatria.pe/feed/": "Peru",
    "https://dsn.pe/feed/": "Peru",
    "https://diariosinfronteras.com.pe/feed/": "Peru",
    "https://diarioelsolcusco.pe/feed/": "Peru",
    "https://diariodelcusco.pe/feed/": "Peru",
    "https://peru21.pe/arcio/rss/": "Peru",
    "https://diariouno.pe/feed/": "Peru",
    "https://trome.pe/arcio/rss/": "Peru",
    "https://enlinea.pe/feed/": "Peru",
    "https://www.connuestroperu.com/?format=feed&type=atom": "Peru",
    "https://proycontra.com.pe/feed/": "Peru",
    "https://www.cronicaviva.com.pe/feed/": "Peru",
    "http://www.peruinforma.com/feed/": "Peru",
    "https://www.losandes.com.pe/feed/": "Peru",
    "https://trujilloinforma.com/feed/": "Peru",
    "https://elchino.pe/feed/": "Peru",
    "https://rpp.pe/feed": "Peru",
    "https://elbocon.pe/arcio/rss/": "Peru",
    "https://elcomercio.pe/arcio/rss/": "Peru",
    "https://gestion.pe/arcio/rss/": "Peru",
    "https://ojo.pe/arcio/rss/": "Peru",
    "https://diariocorreo.pe/arcio/rss/": "Peru",
    "https://lamula.pe/feed/": "Peru",
    "https://larazon.pe/feed/": "Peru",
    "https://www.elnuevodia.com/arc/outboundfeeds/rss/?outputType=xml": "Puerto Rico",
    "https://www.periodicolaperla.com/feed/": "Puerto Rico",
    "https://esnoticiapr.com/feed/": "Puerto Rico",
    "https://www.presenciapr.com/feed/": "Puerto Rico",
    "https://www.vocesdelsurpr.com/feed/": "Puerto Rico",
    "https://www.elexpresso.com/feed/": "Puerto Rico",
    "https://periodicoeloriental.com/feed/": "Puerto Rico",
    "https://lavozdigitalpr.com/feed/": "Puerto Rico",
   }
};
